version: '3.5'

services:
  telnet-proxy:
    build: ./telnet
    container_name: telnet-proxy
    ports:
      - "3333:3333"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  snmp-proxy:
    build: ./snmpwalk
    container_name: snmp-proxy
    ports:
      - "3332:3332"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"